### ISSUE TITLE
Can't load it

### ISSUE THREAD

**Issue by brothermechanic** [the3dadvantage/Modeling-Cloth-2_8#3]
I show problem on video
[2019-05-31 17-21-56.zip](https://github.com/the3dadvantage/Modeling-Cloth-2.8/files/3241612/2019-05-31.17-21-56.zip)

**Comment by the3dadvantage** [comment]
Did you try just installing the zip folder as the addon?
You can also just open the modeling_cloth28.py file in a text editor and run it...

**Comment by brothermechanic** [comment]
Hm, sorry
I tested mode and looks like a problem is in Alternate script path and User script path
Worked in System script path /usr/share/blender/2.80/scripts/addons/SimpleAssetManager
Sorry for noise, i will send bugreport to bf

**Comment by brothermechanic** [comment]
Upd: Alternate script path works
Now i will learn it!)
Thanks for sharing!

**Comment by brothermechanic** [comment]
This is what i get on blender's bugtracker
"Multiple dots in filename make it fails, try to rename your .zip into Modeling-clothing-28.zip"
https://developer.blender.org/T65360

ps: I am very impressed with your addon video review
This is incredible!
